version: "3"
services:
  reverseproxy:
    build:
      context: ../../Nouveau dossier (6)/microservices-project/reverseproxy
    image: raykadri/reverseproxy 
  backend_user:
    build:
      context: ../../Nouveau dossier (6)/microservices-project/udagram-api-user
    image: raykadri/udagram-api-user
  backend_feed:
    build:
      context: ../../Nouveau dossier (6)/microservices-project/udagram-api-feed  
    image: vikrambedi/rest-api-feed
  frontend:
    build:
      context: ../../Nouveau dossier (6)/microservices-project/udagram-frontend  
    image: raykadri/udagram-frontend
